### ISSUE TITLE
Issues with background image draw method

### ISSUE THREAD

**Issue by francescomalatesta** [astef-org/web#1]
On some devices, the background image is not shown in the right way. More info in the next messages.

**Comment by francescomalatesta** [comment]
![screenshot_20170130-204050](https://cloud.githubusercontent.com/assets/1940952/22438580/d41c46ea-e72c-11e6-90e2-5b93dbfa3ba9.png)

On Galaxy Tab 2, Chrome

**Comment by francescomalatesta** [comment]
Tested on Windows 10, with Firefox. Everything seems fine.

**Comment by francescomalatesta** [comment]
@wbigger just tested with a 2013 MacBook, everything seems fine on Chrome and also on Safari! What's your screen resolution?

**Comment by wbigger** [comment]
@francescomalatesta referring to the image that you posted for Galaxy Tab 2, that is exactly what I see on my screen, and it is wrong, since that is only the top-left corner of the original image.

**Comment by francescomalatesta** [comment]
@wbigger yep, but let me know what's your resolution on the MacBook :)

**Comment by wbigger** [comment]
@francescomalatesta oook, it is 1280x800, default screen resolution on a MacBook Pro (Retina, 13-inch, Early 2015).

**Comment by francescomalatesta** [comment]
This is crazy, I can't manage to reproduce it on many, various MacBooks with different resolutions. Can you  also try on other desktop/laptop devices and let me know if it's something isolated?

**Comment by wbigger** [comment]
OK, I will try and I will let you know.

**Comment by wbigger** [comment]
Same issue on my mac also with Firefox and Safari. I will try with another
 To be sure I am doing well, please confirm you are using this
<https://github.com/astef-org/matlab/tree/master/demo_data> data!

**Comment by wbigger** [comment]
Tested on Chrome/Windows 8, it works. The very same dist/bundle.js that I used on my MAC.

**Comment by francescomalatesta** [comment]
Let's use a single version for our experiments. I deployed a test build on

http://astef.hellofrancesco.com

**Comment by wbigger** [comment]
I tried the link with other mac and pc, I cannot reproduce the issue neither :(

**Comment by francescomalatesta** [comment]
Ok, so it seems an anomaly. Let's close this issue and reopen it in the future, if really necessary :) It is ok for you? :)

**Comment by nichel** [comment]
i have the same issue

**Comment by wbigger** [comment]
@nichel has a Mac book pro 15'' with retina display.

**Comment by wbigger** [comment]
I tried several resolutions of my display, with the same issue. If I increase the resolution, I see less image.

**Comment by francescomalatesta** [comment]
Wait, so you can or **cannot** reproduce the anomaly? It's not clear from your previous comments.

Don't think it's something related to retina display, however...

**Comment by wbigger** [comment]
Yes, at last we reproduced the problem with Alessandro's Mac.
However, it seems that are only few cases, so it is fine for me to close
this issue (or change priority/type) and reopen it in the future.

**Comment by francescomalatesta** [comment]
Ok, closing it.
